<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>CGPacksPlus</AssemblyName>
    <Description>Adds some useful features to cybergrind packs.</Description>
    <Version>0.0.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>CGPacksPlus</RootNamespace>
    <NoWarn>IDE1006, IDE0044, IDE0130, IDE0028, IDE0305</NoWarn>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.28" IncludeAssets="compile" />

    <Reference Include="lib/BepInEx/core/BepInEx.dll" />
    <Reference Include="lib/BepInEx/core/0Harmony.dll" />

    <Reference Include="lib/Assembly-CSharp.dll" />
    <Reference Include="lib/UnityEngine.UI.dll" />
    <Reference Include="lib/UnityEngine.UI.dll" />
    <Reference Include="lib/UnityEngine.AssetBundleModule.dll" />
    <Reference Include="lib/Unity.TextMeshPro.dll" />
    <Reference Include="lib/Unity.Addressables.dll" />
    <Reference Include="lib/Unity.ResourceManager.dll" />

    <Reference Include="lib/plog.dll" />
    <Reference Include="lib/plog.unity.dll" />
  </ItemGroup>

  <!-- Going nuclear because I can't figure out how to do this more reasonably -->
  <PropertyGroup>
    <PublicizeAll>true</PublicizeAll>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="Build">
    <CallTarget Targets="CleanCustomArtifacts" />
    <Message Text="Copying files to ./out/" Importance="high" />

    <Copy SourceFiles="./icon.png;./manifest.json;./README.md;./CHANGELOG.md;./LICENSE;$(TargetDir)$(TargetName).dll" DestinationFolder="./out/" />
  
    <Message Text="Finished copying files." Importance="high" />

    <Message Text="Adding files to .zip ..." />
    <ZipDirectory DestinationFile="./whyis2plus2-$(TargetName)-$(Version).zip" Overwrite="true" SourceDirectory="./out" />
    <Message Text="Created zip file." Importance="high" />
  </Target>

  <Target Name="CleanCustomArtifacts" AfterTargets="Clean">
    <Message Text="Clearing custom build artifacts" Importance="high" />
    <RemoveDir Directories="./out" />
    <Delete Files="./whyis2plus2-$(TargetName)-$(Version).zip" />
  </Target>

</Project>
